CFLAGS = -Wshadow -Winit-self -Wredundant-decls -Wcast-align -Wundef -Wfloat-equal -Winline -Wunreachable-code -Wmissing-declarations -Wmissing-include-dirs -Wswitch-enum -Wswitch-default -Weffc++ -Wmain -Wextra -Wall -g -pipe -fexceptions -Wcast-qual -Wconversion -Wctor-dtor-privacy -Wempty-body -Wformat-security -Wformat=2 -Wignored-qualifiers -Wlogical-op -Wno-missing-field-initializers -Wnon-virtual-dtor -Woverloaded-virtual -Wpointer-arith -Wsign-promo -Wstack-usage=8192 -Wstrict-aliasing -Wstrict-null-sentinel -Wtype-limits -Wwrite-strings -Werror=vla -D_DEBUG -D_EJUDGE_CLIENT_SIDE

stringsFunctions.o: stringsFunctions.cpp
	g++ $(CFLAGS) -c stringsFunctions.cpp
main.o: main.cpp
	g++ $(CFLAGS) -c main.cpp
arrayFunctions.o: arrayFunctions.cpp
	g++ $(CFLAGS) -c arrayFunctions.cpp
sorts.o: sorts.cpp
	g++ $(CFLAGS) -c sorts.cpp
arrOfStringsFunctions.o: arrOfStringsFunctions.cpp
	g++ $(CFLAGS) -c arrOfStringsFunctions.cpp
helpingFunctions.o: helpingFunctions.cpp
	g++ $(CFLAGS) -c helpingFunctions.cpp
structNovelFunctions.o: structNovelFunctions.cpp
	g++ $(CFLAGS) -c structNovelFunctions.cpp
Strings.exe: main.o stringsFunctions.o arrayFunctions.o arrOfStringsFunctions.o structNovelFunctions.o sorts.o helpingFunctions.o
	g++ $(CFLAGS) stringsFunctions.o structNovelFunctions.o main.o arrayFunctions.o arrOfStringsFunctions.o sorts.o helpingFunctions.o -o Strings
clean:
	rm main.o stringsFunctions.o arrayFunctions.o arrOfStringsFunctions.o structNovelFunctions.o sorts.o helpingFunctions.o
build: Strings.exe
